-- =====================================================================
-- DASHBOARDOperacional-PCBR — standalone (single-tenant) schema
-- Reconstructed from the live Avante production schema
-- (project ref rcqkmaxkuxllcyjzqbvn), table-by-table, via
-- information_schema / pg_catalog introspection on 2026-07-13.
--
-- Changes vs. Avante:
--   1. organization_id (column + FK to organizaciones) removed from
--      every table that had it — this app is single-tenant.
--   2. clientes: campos_personalizados jsonb removed; the fields it
--      held now live in their own dedicated columns (see NOTE below —
--      most of them already existed as real columns in live Avante
--      *in addition to* campos_personalizados, so 002/migrate_data.mjs
--      merges both sources).
--   3. perfiles: organization_id removed.
--   4. RLS: every table gets a single permissive policy
--      (FOR ALL TO authenticated USING (true) WITH CHECK (true)),
--      matching the pattern already used for configuraciones_app in
--      database/migrations/sql_crear_configuraciones.sql.
--   5. New singleton table configuracion_empresa replaces the
--      branding columns that lived on organizaciones.
--
-- Auto-increment bigint PKs: Avante used a mix of plain sequences
-- (nextval(...) default) and identity columns (some ALWAYS, some BY
-- DEFAULT). All of them are normalized here to
-- `GENERATED BY DEFAULT AS IDENTITY` so that 002/migrate_data.mjs can
-- INSERT rows with their original Avante ids (to keep FK relationships
-- intact) without needing OVERRIDING SYSTEM VALUE. Run the
-- setval(...) calls at the bottom of this file AFTER loading data, or
-- rely on the ones already issued by migrate_data.mjs.
--
-- NOTE / FLAGGED FOR REVIEW:
--   - configuraciones_app in live Avante actually HAS an
--     organization_id column (PK was (clave, organization_id)), even
--     though the reference migration file used as a pattern for RLS
--     does not have it. Per instruction #1 ("quitar organization_id de
--     TODAS las tablas de arriba que la tengan") it is removed here
--     too, restoring PK to (clave) alone — matching the reference file.
--   - documentos_operacionales.dato_operacional_id is a bare bigint
--     with no FK in Avante (points at nothing) — kept as-is.
--   - Avante has several triggers/functions implementing business
--     logic (auto-updating clientes.valor_total, auto-org-id,
--     audit logging into historial_cambios/historial_clientes, and a
--     webhook trigger on mensajes that calls an Avante Edge Function
--     with a hardcoded service_role JWT). NONE of that is reproduced
--     here — only DDL was requested. If the standalone app needs any
--     of that behavior it must be re-implemented at the app layer or
--     as new triggers, reviewed independently (the webhook trigger in
--     particular should NOT be copied verbatim — it embeds a live
--     Avante secret).
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================================================================
-- LEVEL 0 — no FK dependencies on other tables in this file
-- =====================================================================

CREATE TABLE public.estados_br (
  uf text NOT NULL,
  nome text NOT NULL,
  regiao text,
  ibge_id integer,
  ativo boolean NOT NULL DEFAULT true,
  criado_en timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT estados_br_pkey PRIMARY KEY (uf),
  CONSTRAINT estados_br_ibge_id_key UNIQUE (ibge_id),
  CONSTRAINT estados_br_uf_chk CHECK (char_length(uf) = 2),
  CONSTRAINT estados_br_nome_chk CHECK (char_length(nome) > 0)
);

CREATE TABLE public.operarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  iniciales text,
  activo boolean DEFAULT true,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT operarios_pkey PRIMARY KEY (id),
  CONSTRAINT operarios_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.etiquetas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  color text NOT NULL,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT etiquetas_pkey PRIMARY KEY (id)
);

CREATE TABLE public.ia_workflows (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre text NOT NULL,
  descripcion text,
  nodes jsonb NOT NULL DEFAULT '[]'::jsonb,
  edges jsonb NOT NULL DEFAULT '[]'::jsonb,
  activo boolean DEFAULT true,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT ia_workflows_pkey PRIMARY KEY (id)
);

CREATE TABLE public.pipelines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  descripcion text,
  orden integer NOT NULL DEFAULT 0,
  es_predeterminado boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pipelines_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tramites_categorias (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  codigo text NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  color text,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tramites_categorias_pkey PRIMARY KEY (id),
  CONSTRAINT tramites_categorias_codigo_unique UNIQUE (codigo)
);

CREATE TABLE public.salidas (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  fecha timestamp with time zone,
  valor numeric(10,2),
  razon text,
  categoria text,
  subcategoria text,
  observacao text,
  verificado boolean,
  mes integer,
  ano integer,
  creado_en timestamp with time zone DEFAULT now(),
  modificado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT salidas_pkey PRIMARY KEY (id)
);

-- clientes: campos_personalizados dropped; dedicated columns added.
-- fecha_emision_pasaporte / fecha_entrada_brasil are TEXT in live
-- Avante (mixed formats: ISO, DD/MM/YYYY, YYYY/MM/DD) but requested as
-- DATE here — migrate_data.mjs parses/normalizes them before insert.
CREATE TABLE public.clientes (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_kommo text,
  fecha text,
  cpf text,
  nombre text,
  telefono text,
  email text,
  valor_total numeric(10,2) DEFAULT 0,
  pais text,
  ciudad text,
  estado text,
  canal_adquisicion text,
  atendente text,
  creado_en timestamp with time zone DEFAULT now(),
  modificado_en timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  policia_federal text,
  tramite text,
  valor_pago_inicial numeric(10,2) DEFAULT 0,
  fecha_entrada_cliente text,
  recurrencia integer,
  estado_cliente text DEFAULT 'nuevo'::text,
  fecha_ultimo_contacto timestamp with time zone,
  cantidad_tramites integer DEFAULT 0,
  actualizado_en text,
  estado_federal text,
  fecha_nacimiento text,
  estado_civil text,
  sexo text,
  nacionalidad text,
  numero_pasaporte text,
  nombre_madre text,
  nombre_padre text,
  rnm text,
  fecha_entrada_brasil date,
  lugar_entrada_brasil text,
  direccion text,
  numero_refugio text,
  fecha_vencimiento_refugio date,
  fecha_vencimiento_pasaporte date,
  carnet_identidad text,
  fecha_emision_pasaporte date,
  lugar_nacimiento text,
  bot_activo boolean DEFAULT false,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_estado_cliente_check CHECK (estado_cliente = ANY (ARRAY['nuevo'::text, 'verificado'::text, 'inactivo'::text, 'vip'::text]))
);

-- Singleton branding table replacing organizaciones' branding columns.
-- color_texto: no existía en la tabla `organizaciones` live de Avante (la
-- migración 019 que la agregaba nunca llegó a producción), pero el frontend
-- (MarcaSettings.jsx / OrganizationContext.jsx) ya la lee/escribe — se
-- agrega acá para que ese código funcione sin más cambios.
CREATE TABLE public.configuracion_empresa (
  id integer NOT NULL DEFAULT 1,
  nombre text,
  logo_url text,
  color_primario text,
  color_fondo text,
  color_texto text,
  config_cabecera_cliente jsonb DEFAULT '["telefono", "email"]'::jsonb,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT configuracion_empresa_pkey PRIMARY KEY (id),
  CONSTRAINT configuracion_empresa_singleton CHECK (id = 1)
);

-- organization_id removed; PK restored to (clave) alone (see NOTE above).
CREATE TABLE public.configuraciones_app (
  clave text NOT NULL,
  valor text NOT NULL,
  descripcion text,
  actualizado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT configuraciones_app_pkey PRIMARY KEY (clave)
);

-- perfiles keeps its FK to auth.users(id) — every Supabase project has
-- the auth schema. It does NOT create matching auth.users rows; see
-- README for the manual step needed before inserting into perfiles.
CREATE TABLE public.perfiles (
  id uuid NOT NULL,
  nombre text NOT NULL DEFAULT 'Usuario'::text,
  email text,
  rol text DEFAULT 'miembro'::text,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  avatar_url text,
  CONSTRAINT perfiles_pkey PRIMARY KEY (id),
  CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE public.integraciones_whatsapp (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proveedor text NOT NULL DEFAULT 'evolution_api'::text,
  api_url text NOT NULL,
  api_key text NOT NULL,
  instancia text NOT NULL,
  numero_whatsapp text,
  activo boolean DEFAULT true,
  webhook_secret text,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT integraciones_whatsapp_pkey PRIMARY KEY (id)
);

CREATE TABLE public.integraciones_kommo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subdominio text,
  token text,
  webhook_secret text,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT integraciones_kommo_pkey PRIMARY KEY (id)
);

CREATE TABLE public.kommo_field_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kommo_entity text NOT NULL,
  kommo_field_id text NOT NULL,
  kommo_field_name text,
  local_field text NOT NULL,
  local_field_type text NOT NULL,
  is_identifier boolean DEFAULT false,
  CONSTRAINT kommo_field_mappings_pkey PRIMARY KEY (id)
);

CREATE TABLE public.kommo_stage_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kommo_pipeline_id text NOT NULL,
  kommo_pipeline_name text,
  kommo_stage_id text NOT NULL,
  kommo_stage_name text,
  tramite text NOT NULL,
  creado_en timestamp with time zone DEFAULT now(),
  activa_registro boolean NOT NULL DEFAULT false,
  CONSTRAINT kommo_stage_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT kommo_stage_mappings_unique UNIQUE (kommo_pipeline_id, kommo_stage_id)
);

CREATE TABLE public.plantillas_documentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  url_archivo text NOT NULL,
  tipo_contenido text,
  field_mappings jsonb DEFAULT '[]'::jsonb,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT plantillas_documentos_pkey PRIMARY KEY (id)
);

-- =====================================================================
-- LEVEL 1 — depends on level 0 tables
-- =====================================================================

CREATE TABLE public.pipeline_etapas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pipeline_id uuid NOT NULL,
  nombre text NOT NULL,
  codigo text,
  color text NOT NULL DEFAULT '#7c3aed'::text,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pipeline_etapas_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_etapas_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id) ON DELETE CASCADE
);

CREATE TABLE public.tramites_catalogo (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  codigo text NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  categoria_id bigint,
  precio_base numeric(12,2) NOT NULL DEFAULT 0,
  costo_base numeric(12,2) NOT NULL DEFAULT 0,
  margen_objetivo numeric(8,4) NOT NULL DEFAULT 0,
  moneda text NOT NULL DEFAULT 'BRL'::text,
  color text,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  campos_config jsonb DEFAULT '[]'::jsonb,
  costo numeric(12,2) DEFAULT 0, -- NOTE: duplicate-looking column vs costo_base, kept as-is from Avante (see summary)
  CONSTRAINT tramites_catalogo_pkey PRIMARY KEY (id),
  CONSTRAINT tramites_catalogo_codigo_unique UNIQUE (codigo),
  CONSTRAINT tramites_catalogo_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.tramites_categorias(id) ON DELETE SET NULL,
  CONSTRAINT tramites_catalogo_costo_chk CHECK (costo_base >= (0)::numeric),
  CONSTRAINT tramites_catalogo_precio_chk CHECK (precio_base >= (0)::numeric)
);

CREATE TABLE public.documentos_operacionales (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_cliente bigint,
  dato_operacional_id bigint, -- NOTE: no FK in Avante either; kept unconstrained
  tipo_documento text NOT NULL,
  nombre_archivo text NOT NULL,
  url_archivo text NOT NULL,
  "tamaño_bytes" bigint,
  tipo_contenido text,
  orden integer,
  fecha_subida timestamp with time zone NOT NULL DEFAULT now(),
  subido_por text NOT NULL,
  verificado boolean DEFAULT false,
  verificado_por text,
  verificado_en timestamp with time zone,
  estado text DEFAULT 'pendiente'::text,
  motivo_rechazo text,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT documentos_operacionales_pkey PRIMARY KEY (id),
  CONSTRAINT documentos_operacionales_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT documentos_operacionales_estado_check CHECK (estado = ANY (ARRAY['pendiente'::text, 'verificado'::text, 'rechazado'::text]))
);

CREATE TABLE public.historial_clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id bigint NOT NULL,
  usuario_id uuid,
  accion text NOT NULL,
  descripcion text NOT NULL,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT historial_clientes_pkey PRIMARY KEY (id),
  CONSTRAINT historial_clientes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT historial_clientes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE SET NULL
);

CREATE TABLE public.relaciones_clientes (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  cliente_id bigint NOT NULL,
  cliente_relacionado_id bigint NOT NULL,
  tipo_relacion text NOT NULL,
  descripcion text,
  creado_por text,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT relaciones_clientes_pkey PRIMARY KEY (id),
  CONSTRAINT relaciones_clientes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT relaciones_clientes_relacionado_id_fkey FOREIGN KEY (cliente_relacionado_id) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT relaciones_clientes_unique UNIQUE (cliente_id, cliente_relacionado_id),
  CONSTRAINT relaciones_clientes_no_self CHECK (cliente_id <> cliente_relacionado_id)
);

CREATE TABLE public.mensajes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id bigint,
  texto text NOT NULL,
  fecha_recepcion timestamp with time zone DEFAULT now(),
  remitente text DEFAULT 'incoming'::text,
  telefono text,
  media_url text,
  media_type text,
  media_name text,
  tipo text,
  proveedor text,
  leido boolean DEFAULT false,
  operario text,
  CONSTRAINT mensajes_pkey PRIMARY KEY (id),
  CONSTRAINT mensajes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE
);

-- Estas 6 tablas (chat_equipo + las 5 de abajo) se nos habían pasado por
-- alto en la lista original de tablas de negocio; agregadas después de que
-- el front tirara errores de "Could not find the table ...".
CREATE TABLE public.chat_equipo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  mensaje text NOT NULL,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chat_equipo_pkey PRIMARY KEY (id),
  CONSTRAINT chat_equipo_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE
);

CREATE TABLE public.ai_chats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id bigint NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT ai_chats_pkey PRIMARY KEY (id),
  CONSTRAINT ai_chats_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT ai_chats_role_check CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text]))
);

CREATE TABLE public.biblioteca_multimedia (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre text NOT NULL,
  tipo_contenido text NOT NULL,
  url_archivo text NOT NULL,
  tamano integer,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT biblioteca_multimedia_pkey PRIMARY KEY (id)
);

CREATE TABLE public.chat_privado (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  emisor_id uuid NOT NULL,
  receptor_id uuid NOT NULL,
  mensaje text NOT NULL,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chat_privado_pkey PRIMARY KEY (id),
  CONSTRAINT chat_privado_emisor_id_fkey FOREIGN KEY (emisor_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT chat_privado_receptor_id_fkey FOREIGN KEY (receptor_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Singleton (una sola fila, como integraciones_whatsapp/integraciones_kommo)
CREATE TABLE public.configuracion_bot (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bot_activo boolean DEFAULT true,
  horario_inicio time without time zone DEFAULT '09:00:00'::time without time zone,
  horario_fin time without time zone DEFAULT '18:00:00'::time without time zone,
  dias_laborales text[] DEFAULT ARRAY['Mon'::text, 'Tue'::text, 'Wed'::text, 'Thu'::text, 'Fri'::text],
  zona_horaria text DEFAULT 'America/Sao_Paulo'::text,
  template_respuesta text DEFAULT 'Hola {nombre}, en breve el equipo se pondrá en contacto.'::text,
  template_fuera_horario text DEFAULT 'Nuestro horario de atención es de {inicio} a {fin}.'::text,
  umbral_spam integer DEFAULT 3,
  ventana_spam_minutos integer DEFAULT 60,
  cooldown_respuesta_segundos integer DEFAULT 60,
  prompt_ai text,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT configuracion_bot_pkey PRIMARY KEY (id)
);

CREATE TABLE public.documentos_pendientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id bigint,
  url_archivo text NOT NULL,
  nombre_archivo text NOT NULL,
  origen text DEFAULT 'kommo'::text,
  fecha_recepcion timestamp with time zone DEFAULT now(),
  verificado boolean DEFAULT false,
  CONSTRAINT documentos_pendientes_pkey PRIMARY KEY (id),
  CONSTRAINT documentos_pendientes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE
);

CREATE TABLE public.notificaciones_equipo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mensaje text NOT NULL,
  cliente_id bigint,
  leida boolean DEFAULT false,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT notificaciones_equipo_pkey PRIMARY KEY (id),
  CONSTRAINT notificaciones_equipo_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE
);

-- =====================================================================
-- LEVEL 2 — depends on level 1 tables
-- =====================================================================

CREATE TABLE public.entradas (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_kommo text,
  fecha text,
  nombre_pix text,
  valor numeric(10,2),
  servicio text,
  cliente text,
  telefono text,
  email text,
  pais text,
  ciudad text,
  estado text,
  cpf text,
  atendente text,
  utm_source text,
  utm_campaign text,
  utm_content text,
  utm_medium text,
  recorrencia text,
  mes integer,
  ano integer,
  creado_en timestamp with time zone DEFAULT now(),
  modificado_en timestamp with time zone DEFAULT now(),
  id_cliente bigint,
  estado_tramite text DEFAULT 'pendiente'::text,
  fecha_completacion timestamp with time zone,
  operario text,
  observaciones text,
  id_lead integer,
  datos_personalizados jsonb DEFAULT '{}'::jsonb,
  pipeline_id uuid,
  stage_id uuid,
  etiquetas_ids uuid[] DEFAULT '{}'::uuid[],
  CONSTRAINT entradas_pkey PRIMARY KEY (id),
  CONSTRAINT entradas_id_lead_unique UNIQUE (id_lead),
  CONSTRAINT fk_entradas_clientes FOREIGN KEY (id_cliente) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT entradas_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id) ON DELETE SET NULL,
  CONSTRAINT entradas_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.pipeline_etapas(id) ON DELETE SET NULL,
  CONSTRAINT entradas_estado_tramite_check CHECK (estado_tramite = ANY (ARRAY['pendiente'::text, 'esperando_docs'::text, 'procesando'::text, 'cancelada'::text, 'completada'::text]))
);

CREATE TABLE public.notas_tramite (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entrada_id bigint NOT NULL,
  texto text NOT NULL,
  creado_en timestamp with time zone DEFAULT now(),
  creado_por text DEFAULT 'operador'::text,
  CONSTRAINT notas_tramite_pkey PRIMARY KEY (id),
  CONSTRAINT notas_tramite_entrada_id_fkey FOREIGN KEY (entrada_id) REFERENCES public.entradas(id) ON DELETE CASCADE
);

CREATE TABLE public.pagos_tramite (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entrada_id bigint NOT NULL,
  monto numeric NOT NULL,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  nota text,
  creado_por text DEFAULT 'operador'::text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pagos_tramite_pkey PRIMARY KEY (id),
  CONSTRAINT pagos_tramite_entrada_id_fkey FOREIGN KEY (entrada_id) REFERENCES public.entradas(id) ON DELETE CASCADE,
  CONSTRAINT pagos_tramite_monto_check CHECK (monto >= (0)::numeric)
);

CREATE TABLE public.formularios_clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id bigint NOT NULL,
  entrada_id bigint,
  tipo_formulario text NOT NULL,
  estado text DEFAULT 'Completado'::text,
  respuestas jsonb NOT NULL DEFAULT '{}'::jsonb,
  creado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  actualizado_en timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT formularios_clientes_pkey PRIMARY KEY (id),
  CONSTRAINT formularios_clientes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE,
  CONSTRAINT formularios_clientes_entrada_id_fkey FOREIGN KEY (entrada_id) REFERENCES public.entradas(id) ON DELETE SET NULL
);

CREATE TABLE public.historial_cambios (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_entrada bigint,
  id_cliente bigint,
  campo text NOT NULL,
  valor_anterior text,
  valor_nuevo text,
  usuario text DEFAULT 'sistema'::text,
  razon text,
  fecha_cambio timestamp with time zone DEFAULT now(),
  CONSTRAINT historial_cambios_pkey PRIMARY KEY (id),
  CONSTRAINT historial_cambios_id_entrada_fkey FOREIGN KEY (id_entrada) REFERENCES public.entradas(id) ON DELETE CASCADE,
  CONSTRAINT historial_cambios_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.clientes(id) ON DELETE CASCADE
);

CREATE TABLE public.tramites_precios (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tramite_id bigint NOT NULL,
  precio numeric(12,2) NOT NULL,
  costo numeric(12,2) NOT NULL DEFAULT 0,
  moneda text NOT NULL DEFAULT 'BRL'::text,
  vigente_desde date NOT NULL DEFAULT CURRENT_DATE,
  vigente_hasta date,
  activo boolean NOT NULL DEFAULT true,
  observaciones text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tramites_precios_pkey PRIMARY KEY (id),
  CONSTRAINT tramites_precios_tramite_id_fkey FOREIGN KEY (tramite_id) REFERENCES public.tramites_catalogo(id) ON DELETE CASCADE,
  CONSTRAINT tramites_precios_fechas_chk CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),
  CONSTRAINT tramites_precios_precio_chk CHECK (precio >= (0)::numeric),
  CONSTRAINT tramites_precios_costo_chk CHECK (costo >= (0)::numeric)
);

CREATE TABLE public.tramites_requisitos (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tramite_id bigint NOT NULL,
  tipo_dato text NOT NULL,
  tipo_documento text,
  obligatorio boolean NOT NULL DEFAULT true,
  instruciones text,
  orden integer,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tramites_requisitos_pkey PRIMARY KEY (id),
  CONSTRAINT tramites_requisitos_tramite_id_fkey FOREIGN KEY (tramite_id) REFERENCES public.tramites_catalogo(id) ON DELETE CASCADE
);

CREATE TABLE public.pipeline_automatizaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pipeline_id uuid NOT NULL,
  stage_id uuid NOT NULL,
  tipo_accion text NOT NULL,
  mensaje_texto text,
  etapa_destino_id uuid,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT false,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  condiciones jsonb DEFAULT '{}'::jsonb,
  webhook_url text,
  operario_nombre text,
  etiqueta_id uuid,
  ia_workflow_id uuid,
  CONSTRAINT pipeline_automatizaciones_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_automatizaciones_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id) ON DELETE CASCADE,
  CONSTRAINT pipeline_automatizaciones_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.pipeline_etapas(id) ON DELETE CASCADE,
  CONSTRAINT pipeline_automatizaciones_etapa_destino_id_fkey FOREIGN KEY (etapa_destino_id) REFERENCES public.pipeline_etapas(id) ON DELETE SET NULL,
  CONSTRAINT pipeline_automatizaciones_etiqueta_id_fkey FOREIGN KEY (etiqueta_id) REFERENCES public.etiquetas(id) ON DELETE CASCADE,
  CONSTRAINT pipeline_automatizaciones_ia_workflow_id_fkey FOREIGN KEY (ia_workflow_id) REFERENCES public.ia_workflows(id) ON DELETE SET NULL,
  CONSTRAINT pipeline_automatizaciones_tipo_accion_check CHECK (tipo_accion = ANY (ARRAY['mensaje'::text, 'mover_etapa'::text, 'webhook'::text, 'operario'::text, 'etiqueta'::text]))
);

-- =====================================================================
-- handle_new_user — crea automáticamente la fila en `perfiles` cuando se
-- crea un auth.users nuevo (invite-team-member usa
-- supabase.auth.admin.inviteUserByEmail con user_metadata nombre/rol).
-- Empresa única: no hay lógica de organización/onboarding que resolver,
-- a diferencia del trigger equivalente que tenía Avante.
-- =====================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.perfiles (id, nombre, email, rol)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nombre', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'rol', 'miembro')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================================
-- RLS — same simple pattern for every table: authenticated users get
-- full access, no organization-based filtering.
-- =====================================================================

DO $$
DECLARE
  t text;
BEGIN
  FOR t IN
    SELECT unnest(ARRAY[
      'estados_br','operarios','etiquetas','ia_workflows','pipelines',
      'tramites_categorias','salidas','clientes','configuracion_empresa',
      'configuraciones_app','perfiles','integraciones_whatsapp',
      'integraciones_kommo','kommo_field_mappings','kommo_stage_mappings',
      'plantillas_documentos','pipeline_etapas','tramites_catalogo',
      'documentos_operacionales','historial_clientes','relaciones_clientes',
      'mensajes','chat_equipo','ai_chats','biblioteca_multimedia','chat_privado',
      'configuracion_bot','documentos_pendientes',
      'notificaciones_equipo','entradas','notas_tramite',
      'pagos_tramite','formularios_clientes','historial_cambios',
      'tramites_precios','tramites_requisitos','pipeline_automatizaciones'
    ])
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true);',
      t || '_allow_authenticated', t
    );
  END LOOP;
END $$;

-- =====================================================================
-- Initial data: configuracion_empresa (branding values copied from
-- Avante organizaciones.id = 'b4a9f43d-2065-48f2-a5c7-f8c0feacc309',
-- "PLATAFORMA CUBANOS BR"). logo_url still points at Avante's own
-- storage bucket — download and re-upload it to this project's
-- storage separately, then update this row (see README).
-- =====================================================================

INSERT INTO public.configuracion_empresa (id, nombre, logo_url, color_primario, color_fondo, config_cabecera_cliente)
VALUES (
  1,
  'PLATAFORMA CUBANOS BR',
  'https://rcqkmaxkuxllcyjzqbvn.supabase.co/storage/v1/object/public/marca/b4a9f43d-2065-48f2-a5c7-f8c0feacc309/logo_1783719795080.png',
  '#1640D6',
  '#000000',
  '["telefono", "email"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  logo_url = EXCLUDED.logo_url,
  color_primario = EXCLUDED.color_primario,
  color_fondo = EXCLUDED.color_fondo,
  config_cabecera_cliente = EXCLUDED.config_cabecera_cliente;
