-- ===========================================================================
-- Migración 12: Trámites vinculados a varias personas
-- ===========================================================================
-- Un trámite (`entradas`) sigue perteneciendo a un titular (`id_cliente`),
-- pero ahora puede tener personas adicionales vinculadas (ej. un caso de
-- refugio de toda una familia). `get_tramites_portal` es la función que la
-- app móvil de clientes usa para traer, dado un cliente logueado, todos los
-- trámites donde es titular O está vinculado.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS public.entrada_clientes_vinculados (
  id bigint generated by default as identity primary key,
  entrada_id bigint not null references public.entradas(id) on delete cascade,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  creado_en timestamptz default now(),
  unique (entrada_id, cliente_id)
);

CREATE INDEX IF NOT EXISTS idx_entrada_vinculados_cliente ON public.entrada_clientes_vinculados(cliente_id);
CREATE INDEX IF NOT EXISTS idx_entrada_vinculados_entrada ON public.entrada_clientes_vinculados(entrada_id);

ALTER TABLE public.entrada_clientes_vinculados ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'entrada_clientes_vinculados' AND policyname = 'entrada_clientes_vinculados_allow_authenticated') THEN
        CREATE POLICY entrada_clientes_vinculados_allow_authenticated
          ON public.entrada_clientes_vinculados FOR ALL TO authenticated USING (true);
    END IF;
END $$;

-- Función para la app móvil: todos los trámites visibles para un cliente
-- (como titular O como persona vinculada), sin requerir sesión de Supabase
-- Auth (la app se loguea con numero_cliente/clave_acceso, no con auth.users,
-- ver login_cliente_portal en la migración 11).
CREATE OR REPLACE FUNCTION public.get_tramites_portal(p_cliente_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_result jsonb;
BEGIN
    SELECT jsonb_agg(jsonb_build_object(
        'id', e.id,
        'servicio', e.servicio,
        'estado_tramite', e.estado_tramite,
        'creado_en', e.creado_en,
        'es_titular', (e.id_cliente = p_cliente_id),
        'titular', jsonb_build_object('id', c.id, 'nombre', c.nombre),
        'vinculados', COALESCE((
            SELECT jsonb_agg(jsonb_build_object('id', vc.id, 'nombre', vc.nombre))
            FROM public.entrada_clientes_vinculados ecv
            JOIN public.clientes vc ON vc.id = ecv.cliente_id
            WHERE ecv.entrada_id = e.id
        ), '[]'::jsonb)
    ))
    INTO v_result
    FROM public.entradas e
    JOIN public.clientes c ON c.id = e.id_cliente
    WHERE e.id_cliente = p_cliente_id
       OR EXISTS (
           SELECT 1 FROM public.entrada_clientes_vinculados ecv
           WHERE ecv.entrada_id = e.id AND ecv.cliente_id = p_cliente_id
       );

    RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_tramites_portal(bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.get_tramites_portal(bigint) TO authenticated;
